# Generated by Django 4.0.6 on 2022-12-19 20:27

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_letteruser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='letteruser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
