# Generated by Django 4.0.6 on 2022-12-19 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_letteruser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='letteruser',
            managers=[
            ],
        ),
    ]
