# Generated by Django 4.0.6 on 2022-12-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_letteruser_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letteruser',
            options={},
        ),
        migrations.RemoveField(
            model_name='letteruser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='letteruser',
            name='username',
        ),
        migrations.AlterField(
            model_name='letteruser',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='letteruser',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='letteruser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='letteruser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='letteruser',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
