# Generated by Django 4.0.6 on 2023-01-03 07:57

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_letteruser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letteruser',
            name='image',
            field=models.ImageField(default='pfps/default_pfp.jpg', upload_to=authentication.models.upload_path),
        ),
    ]
