# Generated by Django 4.0.6 on 2023-01-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_letteruser_image_review_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letteruser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
