# Generated by Django 4.0.6 on 2023-01-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='russia', max_length=255),
            preserve_default=False,
        ),
    ]
