# Generated by Django 4.1.5 on 2023-01-22 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 22, 22, 20, 51, 790501), null=True),
        ),
    ]
