# Generated by Django 4.1.5 on 2023-02-07 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_alter_order_city_alter_order_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 8, 0, 28, 33, 88641), null=True),
        ),
    ]
